import React from "react";

const Disclaimer = () => {
  return (
    <div className="container">
      <h2>Disclaimer</h2>
      <p>
        We are not licensed lawyers. The information provided here is simplified legal guidance generated by AI. 
        For real legal advice, please consult a certified lawyer.
      </p>
    </div>
  );
};

export default Disclaimer;
